### ISSUE TITLE
Ampersands in i3 4.9

### ISSUE THREAD

**Issue by a-roy** [enkore/i3pystatus#181]
I just updated i3 to the latest version (4.9.1) and now have an issue with ampersands causing modules in i3pystatus not to be displayed. Using the text module, I found that using `&amp;` correctly displays an ampersand. However, I can't make this replacement in other modules which use format strings to generate the text (such as the MPD module).

**Comment by richese** [comment]
i3bar parses output strings either as normal text or as pango markup. Pango seems to require ampersands in the `&amp;` form or some nasty things happen.

AFAIK there is currently no way to set output to pango markup mode in i3pystatus so I am not sure why this happend in the first place. Probably some changes on i3bar side.

I just found this randomly while testing some things that allow the use of pango. This bug does not show for me otherwise.

One possible solution could be to explicitly add `"markup": "none"` to output of each module or `"markup": "pango"` and replace the ampersands.

**Comment by enkore** [comment]
Fixed by #220
