### ISSUE TITLE
Separate master and stable docs

### ISSUE THREAD

**Issue by k1-hedayati** [enkore/i3pystatus#360]
@terminalmage has recently changed weather module and it's docs and added some very interesting features, I was trying to use it with this example from docs
```python
from i3pystatus import Status
from i3pystatus.weather import weathercom

status = Status()

status.register(
    'weather',
    format='{condition} {current_temp}{temp_unit}{icon}[ Hi: {high_temp}] Lo: {low_temp}',
    colorize=True,
    backend=weathercom.Weathercom(
        location_code='94107:4:US',
        units='imperial',
    ),
)

status.run()
```
but in current stable version in PyPi `from i3pystatus.weather import weathercom` fails because `weathercom` modules doesn't exists. So newcomers can't use weather module unless they dig into repo.

If we separate docs for master and stable version issues like this won't raise.

**Comment by terminalmage** [comment]
Should be relatively simple to do this with readthedocs: http://docs.readthedocs.org/en/latest/versions.html

**Comment by k1-hedayati** [comment]
:+1:

**Comment by shoban** [comment]
:+1:

**Comment by enkore** [comment]
Since the move to docs.enkore.de was made due to incohrent/irreproducible build failures on rtfd.io it seems that it now essentially works. I therefore changed the docs URL back to http://i3pystatus.rtfd.io/ . Some older versions aren't available (they still fail to build), but current master and the last release are.
