### ISSUE TITLE
SIGSTOP and SIGCONT are ignored

### ISSUE THREAD

**Issue by hobarrera** [enkore/i3pystatus#370]
[i3bar](https://i3wm.org/docs/userguide.html#_display_mode) sends `SIGSTOP` when the bar is not visible to save battery by avoiding the status-line process from running needlessly.

i3pystatus ignores `SIGSTOP`.

**Comment by Arvedui** [comment]
According to the signal.h manpage `SIGSTOP`, like `SIGKILL`, cannot be ignored or caught.

Thus sending `SIGSTOP` to the i3pystatus process will freeze the process and as a result  the bar, because no new data is received. There is no way a process can prevent that, because that's is handled directly by the kernel.

**Comment by enkore** [comment]
Thanks @arvedui
