### ISSUE TITLE
Click events rerun module

### ISSUE THREAD

**Issue by jmeekr** [enkore/i3pystatus#378]
I have a module subclassed from IntervalModule with a large interval time.  I only want to update my module with the interval time.  Currently it updates every time I click it.

It seems this might be due to `core/__init__.py`'s `_command_endpoint` but I'm not really sure how that works.  The `_command_endpoint` calls `target_module.run()` after `target_module.on_click` which is why I suspect this.

Is there a way to turn off click events from rerunning an individual module?

**Comment by richese** [comment]
No, it is not possible to disable it for one module only.
That call is intentional. A click event will most likely change the state of a module therefore `run` is called after every click event to update modules output with minimal latency.
IntervalModule should not rely on the fact that `run` is called only once per interval because as you noticed it can be called multiple times for various other reasons.

As for some suggestions if you really want to execute something only after a specified interval:
* Run it in separate thread.
* Use a variable to store next execution time:
```python
def init(self):
    self.next_run = time.time()

def run(self):
    if self.next_run <= time.time():
        self.next_run = time.time() + self.interval - 1
        # do stuff

    # do time independent stuff

```

**Comment by jmeekr** [comment]
Awesome, I thought this would be the answer and I'm glad for the clarification.

**Comment by terminalmage** [comment]
I got bitten by this a while back and, going through old issues, noticed this. I've added docs in https://github.com/enkore/i3pystatus/pull/765.
