### ISSUE TITLE
Disable redshift at start

### ISSUE THREAD

**Issue by teto** [enkore/i3pystatus#489]
I find it very annoying that restarting i3pystatus restarts redshift (I use redshfit transitions). 
disabled redshift should be the default IMO.
How to disable it anyway ? should I configure "redshift_parameters" ?

In my config I've done:

```
redshift = status.register("redshift", )
redshift.toggle_inhibit()
```

**Comment by m45t3r** [comment]
This is how the module works, since it starts its own instance of redshift instead of trying to control one already running (redshift does not offer a DBUS interface or something, so AFAIK this is impossible). So the fact that when you restarts i3pystatus restarts redshift is inevitable.

I can add an option to allow setting the inhibit state at startup. However I would rather wait PR #484 to be merged first. Is this reasonable @teto?

**Comment by teto** [comment]
that would be nice. No hurry :)

**Comment by chestm007** [comment]
without getting all hackish, this might have to wait until after
https://github.com/jonls/redshift/pull/54

**Comment by teto** [comment]
I've stopped using redshift
