### ISSUE TITLE
callbacks sudo & ssh-agent issues

### ISSUE THREAD

**Issue by 2Belette** [enkore/i3pystatus#509]
Hi, 
I am trying to use two callbacks for two purposes : one for opening an ssh connection when left clicking on an item and another to execute a program where sudo is needed.

**ssh issue :** 
`    on_leftclick = "urxvt -e ssh user@address"`
this is opening my terminal as expected but asks me my passphrase.
This shouldn't happen as my passphrase is already handle by my ssh-agent.
The strange thing is that if I change it to 
`    on_leftclick = "urxvt"`
and manually do inside the terminal a : 
`    ssh user@address`
This is working without asking my the passphrase.

I checked that in my env the ssh-agent is running correctly and it is the case!

**sudo issue :** 
I am trying to launch a script which needs sudo to work, when I run it through my terminal it asks my my password as expected, doing the same through a callbacks does nothing + issue in my journalctl
`    on_leftclick = "urxvt -e sudo /usr/bin/fdn up",`

error : 
`Dec 22 20:46:44 xps sudo[15161]: pam_unix(sudo:auth): auth could not identify password for [user]`

Any idea?
Many thanks

**Comment by facetoe** [comment]
Have you tried specifying your shell? From the `urxxvt` man page: "If you want to run shell commands, you have to specify the shell".

Maybe something like this will work:

```
urxvt -e bash -c "ssh user@address"
```

**Comment by 2Belette** [comment]
Yep I forgot to mention I tried this as well with the same result..

On December 26, 2016 3:16:36 AM GMT+01:00, facetoe <notifications@github.com> wrote:
>Have you tried specifying your shell? From the `urxxvt` man page: "If
>you want to run shell commands, you have to specify the shell".
>
>Maybe something like this will work:
>
>```
>urxvt -e bash -c "ssh user@address"
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/enkore/i3pystatus/issues/509#issuecomment-269149033

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by facetoe** [comment]
Try adding:

```python
on_leftclick = 'urxvt -e bash -c "env | grep -i ssh > /tmp/sshenv.txt"'
```

And verify that you see you `ssh-agent`'s ENV variables in `/tmp/sshenv.txt` after reloading and clicking the module.

**Comment by 2Belette** [comment]
Thanks for this, I tried and the file is blank.
It is strange as if I do a on_leftclick = 'urxv' and issue a 'env' I can 
see it.


On Mon, Dec 26, 2016 at 01:31:53AM -0800, Lukáš Mandák wrote:
>Try adding:
>
>```python
>on_leftclick = 'urxvt -e bash -c "env | grep -i ssh > /tmp/sshenv.txt"'
>```
>
>And verify that you see you `ssh-agent`'s ENV variables in `/tmp/sshenv.txt` after reloading and clicking the module.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/enkore/i3pystatus/issues/509#issuecomment-269190768

-- 
Benoit

**Comment by facetoe** [comment]
I suspect that when the `bash` shell starts up it is not sourcing whichever file has your `ssh-agent` ENV information in it. How have you configured your `ssh-agent`, do you know where this information is stored? If so, you should be able to source this information before the `ssh` command and have your `ssh-agent` work as expected. 

Another possibility is that you are not using `bash` as your default shell, what is the output of `echo $SHELL`?

**Comment by 2Belette** [comment]
Yes I am not, I am using zsh (echo $SHELL : /usr/bin/zsh)
I can see this in my env
SSH_AUTH_SOCK=/tmp/ssh-ErqMOIivRM9c/agent.1478
SSH_AGENT_PID=1481

Do you think I have to manualy add this before issuing the command 
on_leftclick?

The thing I don't understand is the difference between starting my 
terminal from python/on_leftclick and normal operation, I would expect 
the same behavior ?

Last unsuccesful try:
on_leftclick = 'urxvt -e /usr/bin/zsh -c "ssh mysshserver"'

On Mon, Dec 26, 2016 at 01:45:55AM -0800, Lukáš Mandák wrote:
>I suspect that when the `bash` shell starts up it is not sourcing whichever file has your `ssh-agent` ENV information in it. How have you configured your `ssh-agent`, do you know where this information is stored? If so, you should be able to source this information before the `ssh` command and have your `ssh-agent` work as expected.
>
>Another possibility is that you are not using `bash` as your default shell, what is the output of `echo $SHELL`?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/enkore/i3pystatus/issues/509#issuecomment-269192554

-- 
Benoit

**Comment by richese** [comment]
@2Belette 
I think the problem is in your understanding of how ssh-agent works. I have never used it so I might be completely wrong here but from what I gathered from the ssh-agent man page it looks like ssh-agent is not a session wide daemon (like gpg-agent) but you start it every time you need it. 
Your call should look more like `on_leftclick = 'ssh-agent urxvt -e "ssh myserver"'` and the ssh-agent process should kill itself when you close the terminal.

**Comment by 2Belette** [comment]
thanks for your suggestion but it is actually not working.
I have been able to make it work with : 
```
on_leftclick = 'urxvt -e /usr/bin/zsh -c "export SSH_AUTH_SOCK=/tmp/ssh-ErqMOIivRM9c/ag
ent.1478 && export SSH_AGENT_PID=1481 && ssh mysshserver"'
```
but I don't know if it is the right way to do it.. as this will change during the next reboot...

**Comment by facetoe** [comment]
The `export` commands are not necessary, you should be able to use the following:

```
urxvt -e /usr/bin/zsh -c "SSH_AUTH_SOCK=/tmp/ssh-ErqMOIivRM9c/agent.1478 SSH_AGENT_PID=1481 ssh mysshserver"
```

You are correct that this is a brittle solution as it will not survive reboots, however it does confirm what the issue is here, namely that the `ssh-agent` ENV variables are not available in the `urxvt` process's environment. There are a number of solutions to this, however it would help if you can identify how `ssh-agent` is configured in your setup. What is the output of:

```
ps auxf | grep ssh-agent -C 5
```

**Comment by 2Belette** [comment]
thanks for your help.
Apparently it is started normaly (I use zim and put my identity on it so when my terminal starts it takes a look if ssh-agent is here, if not it asks me the passphrase of my ssh priv key).
```
ps auxf | grep ssh-agent -C 5
user   4994  0.0  0.0  24932  3500 ?        S    11:50   0:00 /usr/bin/zsh
user  18131  0.2  0.1 130236 19000 ?        S    13:16   0:00 urxvt
user  18132  0.3  0.0  40680  7244 pts/5    Ss   13:16   0:01  \_ zsh
user  21666  0.0  0.0  41108  3624 pts/5    R+   13:23   0:00      \_ ps auxf
user  21667  0.0  0.0  10756  2176 pts/5    S+   13:23   0:00      \_ grep --color=auto ssh-agent -C 5
user  18142  0.0  0.0  11160   316 ?        Ss   13:16   0:00 ssh-agent
```

**Comment by richese** [comment]
Processes inherit environment variables from their parent process. In our case the parent process is i3
therefore you need to export SSH_AUTH_SOCK and SSH_AGENT_PID before you start i3 so that every new terminal and shell inherits the same variables.

I use xinit to start Xorg after login so in my case I would just add this line to my .xinitrc:
```shell
eval $(ssh-agent -s)
exec i3
```
So my question is how exactly do you start ssh-agent and i3?

**Comment by 2Belette** [comment]
I think you found it :)
adding eval $(ssh-agent -s) into my .xinitrc makes the tricks :)
by the way my on_leftclick = 'urxvt -e /usr/bin/zsh -c "ssh server"'
If I add ssh-agent before ssh server it asks me the passphrase again

Many thanks you solved me one issue, don't hesitate if you have anything 
in your minde which could help regarding my sudo issue

On Mon, Dec 26, 2016 at 08:15:16AM -0800, Lukáš Mandák wrote:
>Processes inherit environment variables from their parent process. In our case the parent process is i3
>therefore you need to export SSH_AUTH_SOCK and SSH_AGENT_PID before you start i3 so that every new terminal and shell inherits the same variables.
>
>I use xinit to start Xorg after login so in my case I would just add this line to my .xinitrc:
>```shell
>eval $(ssh-agent -s)
>exec i3
>```
>So my question is how exactly do you start ssh-agent and i3?
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/enkore/i3pystatus/issues/509#issuecomment-269223755

-- 
Benoit

**Comment by richese** [comment]
Can't say I don't have any ideas. I think sudo only asks for password if it is running in **interactive shell**. Try running it as command of your shell (also try shell arguments `-i` or `-l`).

I don't know what `/usr/bin/fdn` is supposed to do but it looks to me that you are running the terminal just to enter the password. If that's the case you might want to use a graphical front end for sudo like`gksudo` (from `gksu` package) instead of normal sudo. 
Adding a no password rule for /usr/bin/fdn into your sudoers file might also be an option if the security implications of running it as root without password do not make you shiver 😄.

**Comment by 2Belette** [comment]
Thanks again for your great help.
I found the issue and it was not related to this at the end..
I was trying to use a custom script to start a vpn and I tried to use is
on "on_leftclick" instead of "vpn_up_command"
Now everything is working correctly and I can see my terminal opens and 
asks me a password to execute my script (I also tried in the past the 
sudoers but I try to avoid it)
