### ISSUE TITLE
Is there a way to colorize the text instead of the background for critical_color/alert_color ?

### ISSUE THREAD

**Issue by 2Belette** [enkore/i3pystatus#517]
Hi,
Speaking about mem, disk, temp modules the alert/critical color colorized the background.
Is there a way to colorize the text (like cpu) instead and let the background not changed?
Thanks

**Comment by 2Belette** [comment]
up

**Comment by terminalmage** [comment]
i3pystatus does not control the background color, it merely sets the ``urgent`` per the [i3bar input protocol](https://i3wm.org/docs/i3bar-protocol.html).

From there, it appears that i3 uses the [urgent_workspace](https://i3wm.org/docs/userguide.html#_colors) color definition to handle colorization. This is the the color you see when there is activity in a window on a non-active workspace, or when you enter a different input mode (such as to resize a window).

To make it so that the background is not colorized, we would have to add config options to all modules which set the ``urgent`` flag, which suppress it being set to ``True`` when the alert level is reached.

**Comment by 2Belette** [comment]
Make sense thanks for the explanation!
Perhaps a stupid question but why don't we use the same mechanism used by cpu_temp instead of urgent? This would uniformize mem, disk, temp and cpu with the same look and feel and let others functions (activity on a non-active workspace, resizing..) render like today

**Comment by facetoe** [comment]
You could implement the logic for the custom urgent in the [ColorRangeModule](https://github.com/enkore/i3pystatus/blob/master/i3pystatus/core/color.py#L4) and patch the necessary modules to use this instead of `urgent`. Another option might be to add a configuration mapping globally and have i3pystatus rewrite urgent to `background` key values if the module is in the mapping. You could then define the urgent color per module without having to explicitly patch them.

**Comment by 2Belette** [comment]
@facetoe thanks for the suggestion. would you have any guidance to achieve this? I am not sure how to do that right now..
