### ISSUE TITLE
pycodestyle is crying like a baby again

### ISSUE THREAD

**Issue by enkore** [enkore/i3pystatus#651]
```
+python3 -mpycodestyle --ignore E501,E741,E305,E722 i3pystatus tests
i3pystatus/mpd.py:174:28: W504 line break after binary operator
i3pystatus/network.py:356:16: W504 line break after binary operator
i3pystatus/now_playing.py:163:45: W504 line break after binary operator
i3pystatus/now_playing.py:165:45: W504 line break after binary operator
i3pystatus/reddit.py:78:6: W605 invalid escape sequence '\{'
i3pystatus/reddit.py:78:19: W605 invalid escape sequence '\w'
i3pystatus/reddit.py:78:22: W605 invalid escape sequence '\}'
i3pystatus/reddit.py:79:6: W605 invalid escape sequence '\{'
i3pystatus/reddit.py:79:16: W605 invalid escape sequence '\w'
i3pystatus/reddit.py:79:19: W605 invalid escape sequence '\}'
i3pystatus/reddit.py:80:6: W605 invalid escape sequence '\{'
i3pystatus/reddit.py:80:21: W605 invalid escape sequence '\}'
i3pystatus/reddit.py:80:24: W605 invalid escape sequence '\{'
i3pystatus/reddit.py:80:36: W605 invalid escape sequence '\}'
i3pystatus/window_title.py:59:13: W504 line break after binary operator
i3pystatus/window_title.py:60:17: W504 line break after binary operator
i3pystatus/window_title.py:77:13: W504 line break after binary operator
i3pystatus/window_title.py:78:14: W504 line break after binary operator
i3pystatus/window_title.py:79:14: W504 line break after binary operator
i3pystatus/core/imputil.py:16:17: W504 line break after binary operator
i3pystatus/core/imputil.py:17:17: W504 line break after binary operator
i3pystatus/core/util.py:274:10: W605 invalid escape sequence '\['
i3pystatus/core/util.py:274:10: W605 invalid escape sequence '\]'
i3pystatus/pulseaudio/__init__.py:213:20: W605 invalid escape sequence '\s'
i3pystatus/pulseaudio/__init__.py:213:24: W605 invalid escape sequence '\d'
tests/test_core_util.py:192:19: W605 invalid escape sequence '\['
tests/test_core_util.py:192:27: W605 invalid escape sequence '\]'
```

Does someone know a saner alternative? One that doesn't decide to do start complaining about code it declared fine two days ago?

**Comment by rscholer** [comment]
I personally like [pylint](https://pylint.readthedocs.io/en/latest/), because it does not only test if the code is pep8 compliant, but it also raises errors for missing docstrings, non-descriptive variable names, code duplication, etc. 

The downside to switching to it would be a **massive** overhaul of the code (unless we deactivate some tests), like changing variable names and adding docstrings. We also would need to declare every external module used by i3pystatus' modules in dev-requirements, which is a good idea anyway. The upside would be a healthier code base. 

[Log of all errors found with pylint in it's default configuration](https://gist.github.com/rscholer/98507dd00bca31904092c609790431f8).

**Comment by EgZvor** [comment]
The part of the problem is that specifying ignore arguments on the command line overrides the defaults. So when the new default is added to the list, we have to add it to the command line arguments. Instead we could use `setup.cfg` file with `pycodestyle` section and specify `ignore = E501,W503` there which would append to the default ignore list instead of overriding it.

**Comment by EgZvor** [comment]
Check out https://github.com/enkore/i3pystatus/pull/653

**Comment by enkore** [comment]
» #653
